### ISSUE TITLE
node应用报错

### ISSUE THREAD

**Issue by zhang19980518** [zeabur/zeabur#158]
node 版本 本地18.16.1
本地没报错

但是部署上去后报错
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'component' -> object with constructor 'Object'
    --- property 'vnode' closes the circle
    at JSON.stringify (<anonymous>)
    at Object.n [as set] (index-bd55ab72.js:3093:3655)
    at JD (index-bd55ab72.js:3099:50536)
    at Proxy.recordState (index-bd55ab72.js:3099:50750)
    at Proxy.<anonymous> (index-bd55ab72.js:3093:2235)
    at Proxy.updateSetting (index-bd55ab72.js:3099:50683)
    at Proxy.<anonymous> (index-bd55ab72.js:3093:2235)
    at L (index-9e2af203.js:1:2618)
    at R (index-9e2af203.js:1:2597)
    at we (index-bd55ab72.js:1:68262)

**Comment by MichaelYuhe** [comment]
本地 build 没报错么？看起来是 build 时期的错误，本地只是起开发服务可能是不会受影响的。
以及麻烦提供部署的项目 ID ，后续请到我们的 Discord 社群发帖已获得帮助噢 https://discord.gg/DrdGCvXEyY

**Comment by zhang19980518** [comment]
64ca245d3347371c8eafdd16
部署ID

**Comment by MichaelYuhe** [comment]
本地 build 报错吗？

**Comment by zhang19980518** [comment]
本地build不报错  线上build也不报错

**Comment by zhang19980518** [comment]
解决了

**Comment by zhang19980518** [comment]
内部引用问题  但是奇怪的是本地没事 线上报错 修复引用之后线上没问题了
